#!/usr/bin/env Rscript

#I tested it with a couple of the files in your NN qPCR folder and the results are exact!! 
##I think it can be more elegant, and I would love to hear your thoughts on how to make it that way :) 

data <- read.delim('/Users/abeerobaid/desktop/2019_07_11-LYME_run2_v2.txt', header= TRUE, skip = 108)

labels <- paste(data[1:96,1])
length <- length(labels)


CT <- function(a)
  { 
      
  final_well <- c()
  final_CT <- c()
  
  for (i in 1:length)
    {
      cycle = c()
      blue = c()
      well = c()
      
      if (i <= length)
        {
          x <- grep (paste(unlist(c("^",labels[i],"$")), collapse=''), data[,1])
      
           for (j in x)
          
          {
            well <- c(well, labels[i])
            cycle <- c(cycle, data[j,2])
            blue <- c(blue, as.numeric(data[j,3]))
           }
      
        frame <- data.frame(as.numeric(cycle),as.numeric(blue))
        two.thirds <- (2*(blue[which.max(blue)] - blue[which.min(blue)]))/3
        datas <- (approx(frame[,2],frame[,1],xout=two.thirds))
        final_CT <- c(final_CT,(datas$y))
        final_well <- c(final_well, labels[i])
        }
      }
    final_frame <- data.frame(final_well, final_CT)
    }

frames <- CT(labels)
frames
